version: 2
updates:
  # ---------- GitHub Actions ----------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "advanced-security/oss-maintainers"
    target-branch: "main"
    commit-message:
      prefix: deps
      prefix-development: chore
    labels:
      - "Dependencies"
    cooldown:
      default-days: 3
    groups:
      actions:
        patterns: ["*"]
