name: "reusable-workflows"
version: "0.1.0"

locations:
  - name: "Actions Versions"
    paths:
      - '.github/workflows/*.yml'
    patterns:
      # Actions
      - 'advanced-security/reusable-workflows/.github/workflows/.*\.yml@v([0-9]\.[0-9]\.[0-9])'
