name: Conatiner Build and Release

on:
  workflow_call:
    inputs:
      semver:
        description: "Semantic version of the image"
        type: string
        required: true

      container-file:
        description: "Path to the Dockerfile"
        type: string
        default: "Dockerfile"

      tags:
        description: "Comma-separated list of tags"
        type: string
        default: "latest"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SBOM_PATH: sbom.spdx.json

permissions:
  # to upload SBOM
  id-token: write
  contents: write
  # to upload Docker image
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # latest / main
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            # SemVer 
            type=semver,pattern={{version}},value=${{ inputs.semver }}
            # SemVer, major only
            type=semver,pattern=v{{major}},value=${{ inputs.semver }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: "${{ inputs.docker-file }}"
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sbom: ${{ env.SBOM_PATH }}

      - name: Upload SBOM
        uses: advanced-security/spdx-dependency-submission-action@v0.0.1
        with:
          filePath: ${{ env.SBOM_PATH }}