name: Labeler

on:
  workflow_call:
    inputs:
      configuration-path:
        description: "Path to the labeler configuration file"
        required: false
        type: string
        default: ".github/labeler.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Check if the .github/labeler.yml file exists
    - name: Check for labeler configuration
      id: labeler-config
      env:
        GH_TOKEN: ${{ github.token }}
        CONFIG_PATH: ${{ github.event.inputs.configuration-path }}
      run: |
        set -e
        if [ -f .github/labeler.yml ]; then
          echo "Labeler configuration found"
          echo "config=./.github/labeler.yml" >> $GITHUB_STATE

        elif [[ -f "$CONFIG_PATH" ]]; then
          echo "Labeler configuration found"
          echo "config=$CONFIG_PATH" >> $GITHUB_STATE

        else
          echo "No labeler configuration found"
          echo "Downloading configuration file from advanced-security/reusable-workflows repository"

          # download file using gh cli
          gh api repos/advanced-security/reusable-workflows/contents/.github/labeler.yml -q '.content' | base64 -d > .github/labeler.yml
          echo "config=./.github/labeler.yml" >> $GITHUB_STATE

        fi

    - uses: "actions/labeler@v5"
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: "${{ steps.labeler-config.outputs.config }}"
        sync-labels: true
