# Python Testing Workflow
# 
# - Automatically runs tests on all supported versions of Python
name: Python

on:
  pull_request:
  workflow_call:
    inputs:
      versions:
        description: 'Python versions to test against'
        type: string
        # All Major versions of Python that are currently supported
        default: '3.9,3.10,3.11,3.12'


jobs:
  testing:
    uses: advanced-security/reusable-workflows/.github/workflows/python-testing.yml@v0.1.0
    secrets: inherit
    with:
      versions: ${{ inputs.versions }}

  linting:
    uses: advanced-security/reusable-workflows/.github/workflows/python-linting.yml@v0.1.0
    needs: [ testing ]
    secrets: inherit
    with:
      versions: ${{ inputs.versions }}
